import Head from 'next/head';
import styles from './Category.module.scss';
import Heading from '@modules/common/heading';

export default function Category() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/public/assets/images/favicon.ico" />
			</Head>
			<main className={styles.main}>Category</main>
			<Heading title="Title" />
		</>
	);
}
